import footlocker from "../../assets/png/footLocker.png";
import sidestep from "../../assets/png/sideStep.png";

const nikeairmax = [
  {
    img: footlocker,
    price: "Price",
    num: "€179,99",
    btn: "Best Price",
    size: "Size:",
    size41: "41",
    size42: "42",
    size43: "43",
    size44: "44",
    size45: "45",
    size46: "46",
    viewthisproduct: "View this product as:",
    lockernl: "Foot Locker NL",
  },
  {
    img: sidestep,
    price: "Price",
    num: "€179,99",
    btn: "Best Price",
    size: "Size:",
    size41: "41",
    size42: "42",
    size43: "43",
    size44: "44",
    size45: "45",
    size46: "46",
    viewthisproduct: "View this product as:",
    lockernl: "Foot Locker NL",
  },
  {
    img: footlocker,
    price: "Price",
    num: "€179,99",
    btn: "Best Price",
    size: "Size:",
    size41: "41",
    size42: "42",
    size43: "43",
    size44: "44",
    size45: "45",
    size46: "46",
    viewthisproduct: "View this product as:",
    lockernl: "Foot Locker NL",
  },
  {
    img: sidestep,
    price: "Price",
    num: "€179,99",
    btn: "Best Price",
    size: "Size:",
    size41: "41",
    size42: "42",
    size43: "43",
    size44: "44",
    size45: "45",
    size46: "46",
    viewthisproduct: "View this product as:",
    lockernl: "Foot Locker NL",
  },
];

export default nikeairmax;
